runtime: nodejs14

instance_class: F2

env: standard

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5

# Optional: Add any additional configuration settings here.